name: snowman
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_stetho: ^0.5.2
  sqflite: ^1.3.1+1
  get_it: ^4.0.2
  rxdart: ^0.24.1
  flutter_icons: ^1.1.0
  custom_rounded_rectangle_border: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "logo"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFBE00"
  adaptive_icon_foreground: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - logo.png